feat: add graasp branding and show all platforms
graasp/graasp-auth pull request #450
Opened 2024-09-12 12:49 UTC by pyphilia

<img width="1408" alt="Screenshot 2024-09-12 at 14 47 10" src="https://github.com/user-attachments/assets/1e2d69cb-582a-4301-a926-ed3420a13ac7">

close #448

2024-09-12 14:27 UTC, ReidyT requested changes
Thanks for this PR! I really like it 🔥. I tried to reverse some of them, but finally I think it's better the way you did.

![image](https://github.com/user-attachments/assets/d34ef46e-47dc-478d-9167-871e24b30ba1)

I would just add more top and left margin to the branding. Also, on mobile, I'm not a big fan of having the branding and the Graasp icon above the login. Maybe we could merge the two on mobile?

![image](https://github.com/user-attachments/assets/32b83fd3-0a79-471a-ae3c-5affe1ceb672)

Also, it's possible I misunderstood, but I thought we should avoid the `*` in the placeholder, shouldn't we?

2024-09-12 14:27 UTC, ReidyT commented on cypress/e2e/SignUp.cy.ts
> +    it.only('Sign Up Is Available When Accepting All Terms', () => {
```suggestion
    it('Sign Up Is Available When Accepting All Terms', () => {
```

2024-09-12 14:27 UTC, ReidyT commented on src/components/BrandingLogo.tsx
> +    <div style={{ position: 'absolute', top: 0, left: 0 }}>
I would increase the position a bit

2024-09-12 14:27 UTC, ReidyT commented on src/components/LeftContentContainer.tsx
>            backgroundImage: `url("data:image/svg+xml,%3Csvg width='100' height='20' viewBox='0 0 100 20' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M21.184 20c.357-.13.72-.264 1.088-.402l1.768-.6
I know that it was not a change from this PR, but we should extract this in a const!

2024-09-12 14:27 UTC, ReidyT commented on src/components/SignUp.tsx
> +            disabled={!userHasAcceptedAllTerms || !email.length || !name.length}
🥳

2024-09-12 14:27 UTC, ReidyT commented on src/langs/de.json
> +  "NAME_FIELD_LABEL": "Name*",
I thought we should remove the `*`?

2024-09-13 14:49 UTC, spaenleh commented on src/components/LeftContentContainer.tsx
> +              color="#1ECAA5"
These are defined in the `ACCENT_COLORS` in ui.

2024-09-17 09:26 UTC, merged