fix: validate email with enter
graasp/graasp-auth pull request #483
Opened 2024-10-21 13:37 UTC by spaenleh

close #475

2024-10-23 11:45 UTC, pyphilia requested changes
LGTM, but you left an `.only`!

2024-10-23 11:45 UTC, pyphilia commented on cypress/e2e/signinWithPassword.cy.ts
> +  it.only('Sign In With Wrong Password', () => {
Remove.

2024-10-23 11:45 UTC, pyphilia commented on src/components/common/Adornments.tsx
> +);
Isn't it a better convention to have a single component per file?

2024-10-23 11:49 UTC, ReidyT approved these changes
LGTM 🐦‍🔥

2024-10-23 11:49 UTC, ReidyT commented on cypress/e2e/signinWithPassword.cy.ts
> +  it.only('Sign In With Wrong Password', () => {
```suggestion
  it('Sign In With Wrong Password', () => {
```

2024-10-23 12:04 UTC, spaenleh commented on cypress/e2e/signinWithPassword.cy.ts
> +  it.only('Sign In With Wrong Password', () => {
💀

2024-10-24 12:06 UTC, pyphilia approved these changes

2024-10-24 15:19 UTC, merged