translate to arabic
graasp/graasp-auth pull request #81
Opened 2023-04-26 08:46 UTC by HusamJubran

2023-04-26 11:48 UTC, pyphilia commented
It looks good to me, I'll let you:
- add a language selector
- make the direction dynamic given the language
- clean comments

2023-05-26 08:25 UTC, pyphilia requested changes
Thanks for the PR, see my comments below.

2023-05-26 08:25 UTC, pyphilia commented on public/index.html
> +    <!--<script>document.dir = 'rtl';</script>-->
Remove this?

2023-05-26 08:25 UTC, pyphilia commented on src/components/Root.tsx
> +            </Select>
As mentioned, use `@graasp/translations`'s `langs` to get all the available languages.

2023-05-26 08:25 UTC, pyphilia commented on src/components/Root.tsx
> +  const [curr_lang, setCurr_lang] = React.useState('en');
In JS we use camel case so `currentLang` and `setCurrentLang`

2023-05-26 08:25 UTC, pyphilia commented on src/components/Root.tsx
> +const rtlTheme = { ...theme, direction: 'rtl' };
I think you can use `isRtl` to define one theme (define in the component)

2023-05-26 08:25 UTC, pyphilia commented on src/components/Root.tsx
> +});
Define one cache given `isRtl` (in the component)

2023-05-26 08:25 UTC, pyphilia commented on src/components/Root.tsx
> +    setCurr_lang(event.target.value);
Normally you can get the direction with `i18n.dir()`

2023-08-04 14:11 UTC, pyphilia commented
@spaenleh I've taken over this PR, you can review it <3

2023-08-04 14:28 UTC, spaenleh requested changes
Nice ! I have left some comments. Not sure why some packages were added. 

Can you provide a screenshot of the footer with the language select that would be nice 🖼️

2023-08-04 14:28 UTC, spaenleh commented on package.json
> +    "react-scripts": "5.0.1",
remove

2023-08-04 14:28 UTC, spaenleh commented on src/typings.d.ts
What is `stylis` used for ?

2023-08-04 14:49 UTC, pyphilia commented on package.json
> +    "@emotion/cache": "11.10.7",
We need some packages for RTL support (hidden in graasp-ui)

2023-08-04 14:50 UTC, pyphilia commented
<img width="1462" alt="Screenshot 2023-08-04 at 16 49 58" src="https://github.com/graasp/graasp-auth/assets/11229627/ecfef429-346e-4ec9-86ba-99ed9434cc5a">
<img width="1448" alt="Screenshot 2023-08-04 at 16 50 09" src="https://github.com/graasp/graasp-auth/assets/11229627/2eab55d1-a24f-4d86-8cd3-09fc91701fa7">
The language select is a bit hidden because of react query aha

2023-08-04 14:58 UTC, spaenleh commented on package.json
> +    "@emotion/cache": "11.10.7",
Ah I see from [the docs](https://mui.com/material-ui/guides/right-to-left/) Nice !

2023-08-04 15:08 UTC, spaenleh approved these changes
Nice ! Just be careful as the language select might be just under the Captcha badge in the lower right corner 😅

2023-08-07 13:44 UTC, merged